import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { InvoicePreview } from '../components/invoice/InvoicePreview'

/* ─── Build the exact invoice markup for ANY invoice object ────
   This is the fix for the "WhatsApp/Email/Preview sab ek jaisa
   behave karte hain" bug — earlier code read whatever invoice
   preview happened to already be mounted in the DOM (which was
   often the currently-open draft, not the invoice actually
   clicked). Rendering straight from the `inv` object removes
   that dependency entirely.                                    */
export function renderInvoiceMarkup(inv) {
  return renderToStaticMarkup(
    createElement(InvoicePreview, {
      inv,
      items: inv.items || [],
      currency: inv.currency || '₹',
      discPct: inv.discPct || 0,
      taxPct: inv.taxPct || 18,
      template: inv.template || 'modern',
      status: inv.status || 'sent',
    })
  )
}

const PRINT_DOC_HEAD = `<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    width: 210mm; min-height: 297mm;
    font-family: 'Plus Jakarta Sans', sans-serif;
    background: #fff; color: #1a1a2e;
    -webkit-print-color-adjust: exact; print-color-adjust: exact; color-adjust: exact;
  }
  body { padding: 0; }
  .invoice-wrap { width: 210mm; min-height: 297mm; background: #fff; display: flex; flex-direction: column; position: relative; }
  @media print { @page { size: A4 portrait; margin: 0; } html, body { margin: 0; padding: 0; } .invoice-wrap { page-break-after: avoid; } }
  table { border-collapse: collapse; }
</style>`

function buildPrintDocument(inv, { autoPrint = false } = {}) {
  const inner = renderInvoiceMarkup(inv)
  const autoPrintScript = autoPrint
    ? `<script>window.onload=function(){window.print();setTimeout(function(){window.close();},2000);}<\/script>`
    : ''
  return `<!DOCTYPE html><html><head><title>${inv.no || 'Invoice'}</title>${PRINT_DOC_HEAD}${autoPrintScript}</head><body><div class="invoice-wrap">${inner}</div></body></html>`
}

/* Opens a print-ready tab for the given invoice and triggers the
   browser print dialog (also usable as "Save as PDF").          */
export function openPrintWindow(inv) {
  const w = window.open('', '_blank')
  if (!w) return null
  w.document.write(buildPrintDocument(inv))
  w.document.close()
  w.focus()
  setTimeout(() => w.print(), 700)
  return w
}

/* ─── Real PDF blob generation (for Web Share API attachments) ── */
export async function generateInvoicePdfBlob(inv) {
  const container = document.createElement('div')
  container.style.position = 'fixed'
  container.style.left = '-99999px'
  container.style.top = '0'
  container.style.width = '210mm'
  container.style.background = '#fff'
  container.innerHTML = renderInvoiceMarkup(inv)
  document.body.appendChild(container)

  try {
    // Let fonts/layout settle before rasterizing
    await new Promise(r => setTimeout(r, 60))
    const canvas = await html2canvas(container, { scale: 2, useCORS: true, backgroundColor: '#ffffff' })
    const imgData = canvas.toDataURL('image/jpeg', 0.95)
    const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = (canvas.height * pageWidth) / canvas.width
    pdf.addImage(imgData, 'JPEG', 0, 0, pageWidth, pageHeight)
    const blob = pdf.output('blob')
    return blob
  } finally {
    document.body.removeChild(container)
  }
}

function buildWhatsAppMessage(inv, attached) {
  const attachLine = attached
    ? '📎 PDF is attached with this message.'
    : '📎 The PDF has been opened for download — please save it and attach it here.'
  return `Hi ${inv.clientName || 'Client'},\n\nYour invoice *${inv.no}* is ready!\n\n📋 *Invoice Details:*\nAmount: *${inv.total}*\nDate: ${inv.date}\nBusiness: ${inv.bizName || ''}\n\n${attachLine}\n\n_Generated by Zerofy Invoice Generator_\nhttps://www.zerofy.co.in`
}

function buildEmailBody(inv, attached) {
  const attachLine = attached
    ? '📎 The PDF is attached to this email.'
    : '📎 The PDF has been opened in your browser — please save it and attach it before sending.'
  return `Hi ${inv.clientName || 'Client'},\n\nPlease find your invoice details below:\n\nInvoice No: ${inv.no}\nDate: ${inv.date}\nAmount: ${inv.total}\n\nBusiness: ${inv.bizName || ''}\n\n${attachLine}\n\nThank you for your business!\n\nRegards,\n${inv.bizName || ''}`
}

/* ─── WhatsApp share — auto-attaches the PDF via the native
   share sheet when the browser/device supports it (Web Share
   API level 2). Falls back to opening the PDF for download +
   WhatsApp pre-filled with the message when it isn't supported
   (desktop browsers mostly).                                   */
export async function shareViaWhatsApp(inv) {
  try {
    const blob = await generateInvoicePdfBlob(inv)
    const file = new File([blob], `${inv.no || 'invoice'}.pdf`, { type: 'application/pdf' })
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        files: [file],
        title: `Invoice ${inv.no}`,
        text: buildWhatsAppMessage(inv, true),
      })
      return
    }
    // Fallback: download PDF + open WhatsApp with message pre-filled
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${inv.no || 'invoice'}.pdf`
    document.body.appendChild(a)
    a.click()
    a.remove()
    setTimeout(() => URL.revokeObjectURL(url), 4000)
  } catch (err) {
    if (err?.name === 'AbortError') return // user cancelled the share sheet
    console.error('WhatsApp share error:', err)
    openPrintWindow(inv)
  } finally {
    const phone = inv.clientPhone ? `91${inv.clientPhone}` : ''
    const waUrl = `https://wa.me/${phone}?text=${encodeURIComponent(buildWhatsAppMessage(inv, false))}`
    setTimeout(() => window.open(waUrl, '_blank'), 600)
  }
}

/* ─── Email share — same auto-attach-if-possible approach. ──── */
export async function shareViaEmail(inv) {
  try {
    const blob = await generateInvoicePdfBlob(inv)
    const file = new File([blob], `${inv.no || 'invoice'}.pdf`, { type: 'application/pdf' })
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        files: [file],
        title: `Invoice ${inv.no} from ${inv.bizName || 'Zerofy'}`,
        text: buildEmailBody(inv, true),
      })
      return
    }
    // Fallback: download PDF + open default mail client with body pre-filled
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${inv.no || 'invoice'}.pdf`
    document.body.appendChild(a)
    a.click()
    a.remove()
    setTimeout(() => URL.revokeObjectURL(url), 4000)
  } catch (err) {
    if (err?.name === 'AbortError') return
    console.error('Email share error:', err)
    openPrintWindow(inv)
  } finally {
    const subject = `Invoice ${inv.no} from ${inv.bizName || 'Zerofy'}`
    const body = buildEmailBody(inv, false)
    setTimeout(() => {
      window.location.href = `mailto:${inv.clientEmail || ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    }, 600)
  }
}
